apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: realworld-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: realworld-app:latest
          name: realworld-app
          imagePullPolicy: Never
          ports:
            - containerPort: 4100